### ISSUE TITLE
チャットフォームの高さがおかしい

### ISSUE THREAD

**Issue by chigichan24** [Mori-Atsushi/YouTubeSync#122]
プレイリストに動画が入ってない時のチャットの表示が崩れている
![screenshot_20171205-133606](https://user-images.githubusercontent.com/7840108/33590528-4f5417dc-d9c3-11e7-8fb3-6a3363304a74.jpg)

**Comment by Mori-Atsushi** [comment]
これ、動画を入れてる入れてない関係なく、ただただチャットの数が少なくて一番下まで来てないだけなんよね。
チャットを下詰にするようにしないといけない。
