### ISSUE TITLE
動画情報の表示変更

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSync#15]
再生時間、公開日、視聴回数を表示

* 再生中の動画部分
* 検索結果、プレイリストのリスト表示

参考：https://xd.adobe.com/view/41e0cb0b-9168-40d3-948b-1882b7d5feef/screen/cc58e1a1-9dcf-4223-9011-69e7702fc665/-

**Comment by chigichan24** [comment]
公開日時の実装は終了．再生回数はAPI待ち．

**Comment by Mori-Atsushi** [comment]
再生回数実装されました。

**Comment by chigichan24** [comment]
thx

**Comment by chigichan24** [comment]
apiがいい感じになると聞いたのでやる．
