### ISSUE TITLE
動画の再生位置を表示

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSync#16]
シークバーを表示（シークはできない）

参考：https://xd.adobe.com/view/41e0cb0b-9168-40d3-948b-1882b7d5feef/screen/cc58e1a1-9dcf-4223-9011-69e7702fc665/-

**Comment by chigichan24** [comment]
YoutubeなFragmentをいい感じにラップしつつ，シークバーもどきをくっつける．
