### ISSUE TITLE
readmeの余計な文字コードを削除する

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSync#24]
![2017-11-05 19 04 27](https://user-images.githubusercontent.com/13435109/32413805-a01a7450-c25c-11e7-9afb-ca410cf9a45d.png)

**Comment by chigichan24** [comment]
edit押してみたんですけど，この赤丸は意図して置いたんですかか？
<img width="276" alt="screen shot 2017-11-06 at 19 28 16" src="https://user-images.githubusercontent.com/7840108/32436855-c0f5a876-c328-11e7-86af-e4a1c2dc4b00.png">

**Comment by Mori-Atsushi** [comment]
ノー、electronのバグで日本語入力中にdeleteを押すと、完全に消えなくて余計な文字コードが残るねん。
赤丸はそれを表しているので、それを消せばOK
