### ISSUE TITLE
ルーム作成時のエラーを通知する。

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSync#71]
カラムの中に空がある場合。
サーバ側のエラー

**Comment by Kousuke-N** [comment]
toastとかでいいですか？

**Comment by Kousuke-N** [comment]
そもそもカラムの空とはこっちが送るデータに不足があったときということですか？

**Comment by Mori-Atsushi** [comment]
アカウント作成時のエラーを参照してね

**Comment by Mori-Atsushi** [comment]
通知はSnackbarをつかってください。
ルーム作成はルーム名と説明を両方書かないといけないので、どちらかが空だったら送信前にエラーを吐いてください。
