### ISSUE TITLE
時間情報の修正

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSync#79]
SimpleDateFormatではなく、android.text.format.DateFormat を使ったほうがいいそうです。
端末に設定されているロケーションを取得する。

**Comment by chigichan24** [comment]
は？

**Comment by Kousuke-N** [comment]
@chigichan24 さんのは？ってどういう意味なんですか？

**Comment by Mori-Atsushi** [comment]
僕のタイプミスに対する指摘で、僕が直したので、意味がわからなくなってるだけなので気にしないで
